### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by 0xC0ba1t** [ClarkFieseln/FPGA_HW_SIM_FWK_2#1]
Hi, this is very interesting and useful project, but is it dead or unmaintained?
Thanks!

**Comment by ClarkFieseln** [comment]
Do you have a feature proposal or any issue to report?
I will come back to my TODO list some time, but I have no deadline for that.
In that sense I would say that the project is not dead or unmaintained.

**Comment by ClarkFieseln** [comment]
As I heard nothing from you since your last message I will close this issue assuming you have no further questions.
Don't hesitate to open new issues otherwise.
You can check the new release with changes introducing a new example based on "synchronized" simulations with circuitjs.
